name: 'compas-actions.docs'
description: 'Build docs for COMPAS or its plugins'

inputs:
  dest:
    description: 'destination folder of built docs'
    required: true
    default: 'deploy'
  build-to-subfolder:
    description: 'whether to build documentation to a subfolder according to the commit type'
    required: true
    default: 'false'
  update-doc-versions:
    description: 'whether to update the list of doc versions'
    required: true
    default: 'false'
  doc-versions-path:
    description: 'the path of doc versions list'
    required: true
    default: 'doc_versions.txt'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        sudo apt-get install graphviz
        python -m pip install --upgrade pip
        python -m pip install cython --install-option="--no-cython-compile"
        python -m pip install --no-cache-dir -r requirements-dev.txt
  
    - shell: bash
      run: invoke docs

    - shell: bash
      run: |
        if [[ ${{ inputs.build-to-subfolder }} == "true" ]] then
          # Get branch/tag/latest name from git
          GITHUB_REF_REGEX="tags/v[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}|(pull/[0-9]+)|heads/main"
          if [[ $GITHUB_REF =~ $GITHUB_REF_REGEX ]]; then
              if [[ $BASH_REMATCH = pull* ]]; then
                  echo This is a pull request
                  FOLDER_NAME=pull_${BASH_REMATCH##*/}
              elif [[ $BASH_REMATCH = tags/* ]]; then
                  echo This is a version tag
                  FOLDER_NAME=${BASH_REMATCH##*/v}
                  echo "::set-output name=current_patch::$FOLDER_NAME"
              else
                  echo This is a commit to main branch
                  FOLDER_NAME=latest
              fi;
          fi;
          mkdir -p deploy/$FOLDER_NAME && mv -T dist/docs deploy/$FOLDER_NAME/
          echo "Docs is built at ${{ inputs.dest }}/$FOLDER_NAME/"
        else
          mkdir -p ${{ inputs.dest }} && mv -T dist/docs ${{ inputs.dest }}
          echo "Docs is built at ${{ inputs.dest }}"
        fi;